version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: renovarsaber-db
    restart: no
    environment:
      POSTGRES_DB: renovarsaber_db
      POSTGRES_USER: renovarsaber_user
      POSTGRES_PASSWORD: renovarsaber_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - renovarsaber-network

volumes:
  postgres_data:

networks:
  renovarsaber-network:
    driver: bridge