CREATE TABLE usuarios (
      id UUID PRIMARY KEY,
      nome VARCHAR(100) NOT NULL,
      email VARCHAR(150) NOT NULL UNIQUE,
      senha VARCHAR(255) NOT NULL,
      data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);